apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrsbot-stats-handler-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrsbot-stats-handler
  template:
    metadata:
      labels:
        app: icrsbot-stats-handler
    spec:
      containers:
      - name: icrsbot-stats-handler
        image: localhost:32000/icrsbot-stats-handler  # Replace with your Python Docker image and tag
        ports:
        - containerPort: 5000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        volumeMounts:
          - name: postgres-ini 
            mountPath: /app/postgres.ini
            subPath: postgres.ini
            readOnly: true
          - name: discord-bot-secret
            mountPath: /app/settings.json
            subPath: settings.json
            readOnly: true
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-bot-secret 
                key: discord_token
          - name: SERVER_IP
            valueFrom:
              secretKeyRef:
                name: access-server-secret 
                key: access_server_ip
      volumes:
        - name: postgres-ini 
          secret:
            secretName: postgres-ini-secret 
        - name: discord-bot-secret
          secret:
            secretName: discord-bot-secret
            items:
              - key: discord_settings
                path: settings.json
