apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrsbot-printer-handler-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrsbot-printer-handler
  template:
    metadata:
      labels:
        app: icrsbot-printer-handler
    spec:
      containers:
      - name: icrsbot-printer-handler
        image: localhost:32000/icrsbot-printer-handler  # Replace with your Python Docker image and tag
        ports:
        - containerPort: 5000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        env:
        - name: TZ
          value: Europe/London
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: printer_status_channel_webhook
        volumeMounts:
        - name: printer-config
          mountPath: /app/settings.json
          subPath: settings.json
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

      volumes:
        - name: printer-config
          configMap:
            name: printer-config
            items:
              - key: printer_config
                path: settings.json
