apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrsbot-file-handler-deployment
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrsbot-file-handler
  template:
    metadata:
      labels:
        app: icrsbot-file-handler
    spec:
      containers:
        - name: icrsbot-file-handler
          image: icroboticssociety/discord-scp # Replace with your Python Docker image and tag
          ports:
            - containerPort: 5000 # Port your Python application is listening on
          imagePullPolicy: "Always"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: discord_token
            - name: SLICER_PW
              valueFrom:
                secretKeyRef:
                  name: slicer-secret
                  key: slicer_password
            - name: SLICER_USER
              valueFrom:
                secretKeyRef:
                  name: slicer-secret
                  key: slicer_username
            - name: SLICER_ADDR
              valueFrom:
                secretKeyRef:
                  name: slicer-secret
                  key: slicer_address
            - name: TARGET_PATH
              valueFrom:
                secretKeyRef:
                  name: slicer-secret
                  key: slicer_path
            - name: FILE_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: file_channel_id
          volumeMounts:
            - name: discord-bot-secret
              mountPath: /app/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: discord-bot-secret
          secret:
            secretName: discord-bot-secret
            items:
              - key: discord_settings
                path: settings.json
