apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrsbot-printer-features-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrsbot-printer-features
  template:
    metadata:
      labels:
        app: icrsbot-printer-features
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: icrsbot-printer-features
        image: localhost:32000/icrsbot-printer-features  # Replace with your Python Docker image and tag
        ports:
        - containerPort: 5000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-bot-secret
                key: discord_token
