on:
  push:
    branches:
    - master
    paths:
      - 'file_handler/**'
      - '.github/workflows/file_handler.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        run: |
          cd file_handler
          ./docker_build.sh ${GITHUB_SHA}
          kubectl set image deployments/icrsbot-file-handler-deployment icrsbot-file-handler=localhost:32000/icrsbot:${GITHUB_SHA}
