on:
  push:
    branches:
    - master
    paths:
      - 'registration/**'
      - '.github/workflows/registration.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        run: |
          cd registration
          ./docker_build.sh ${GITHUB_SHA}
          kubectl set image deployment/icrsbot icrsbot=localhost:32000/icrsbot:${GITHUB_SHA}
